// Browser-side workbook builders. Build the RMS EDM and Verisk CEDE workbooks
// in the page with the ExcelJS browser build (window.ExcelJS), from the same
// canonical state the server functions used. Ported from
// netlify/functions/export-{edm,cede}.mjs so export runs with no backend.

import { RMS_OCC, RMS_CONSTR, RMS_GEO } from "../shared/rms-codes.mjs";
import { AIR_OCC, AIR_CONSTR, AIR_GEO } from "../shared/cede-codes.mjs";
import { mapPerils } from "../shared/canonical.mjs";
import { writeReadMe, writeSheet, writeDataQuality } from "../shared/exporter-common.mjs";
import { PALETTE } from "../shared/palette.mjs";

function newWorkbook() {
  const ExcelJS = window.ExcelJS;
  if (!ExcelJS) throw new Error("ExcelJS not loaded");
  const wb = new ExcelJS.Workbook();
  wb.creator = "CERA® AI — EDM & CEDE Converter";
  wb.created = new Date();
  return wb;
}

export function buildEdmWorkbook(state) {
  const { locations, accounts, policies } = state;
  if (!Array.isArray(locations) || !locations.length) throw new Error("No locations to export");
  const wb = newWorkbook();

  writeReadMe(wb.addWorksheet("ReadMe"),
    "CERA® → RMS EDM (MRI) Export",
    "Populated Moody's RMS EDM import template",
    [
      ["WHAT THIS FILE IS", "An MRI-compatible exposure import for Moody's RMS Risk Modeler 2.0, generated by CERA® AI from a broker schedule. Sheet names and field names follow the standard RMS taxonomy."],
      ["HOW TO READ IT", ""],
      ["Account sheet", "One row per legal insured entity. RMS treats accounts as the wrapper for one or more policies."],
      ["Policy sheet", "One row per notional blanket policy: LOB, dates, blanket limit and deductible, HU 2% / EQ 5% deductibles, perils covered, BI indemnity period."],
      ["Location sheet", "One row per insured location, with full RMS-coded fields (occupancy, construction, geocode level), per-state peril coverage, six secondary modifiers, and per-field source flags."],
      ["DataQuality sheet", "Coverage statistics: how many rows had each field supplied by the broker vs estimated by CERA® AI."],
      ["Methodology sheet", "How every assumption was made: classifier vocabulary, TIV split ratios, peril coverage by state, secondary modifier defaults."],
      ["", ""],
      ["WHAT IS REAL vs ESTIMATED", ""],
      ["Pale green cells", "Value taken directly from the broker submission (SUPPLIED)."],
      ["Pale pink cells", "Value estimated by CERA® AI (ESTIMATED). Flag for underwriter review."],
      ["Pale yellow cells", "Partial: some components supplied, others derived from split ratios (PARTIAL)."],
      ["Light grey cells", "Derived from supplied data by deterministic rule (DERIVED), for example peril coverage from state."],
      ["", ""],
      ["CODE TAXONOMIES", "Occupancy and construction codes follow standard RMS code dictionaries (322 General Office, 343 Industrial Warehouse, 121 Reinforced Concrete, 132 URM, etc.). Production exports can be cross-walked to the exact RM-version codes your Risk Modeler instance expects."],
      ["CANONICAL EXPOSURE OBJECT", "This file is one of two serialisations from a single canonical exposure object. The companion Verisk CEDE file uses identical locations, classifications and TIV splits; only the code dictionaries, sheet names and geocode taxonomy differ."],
    ]);

  writeDataQuality(wb.addWorksheet("DataQuality"), locations);

  const accSheet = wb.addWorksheet("Account");
  const accHeaders = [
    { key: "AccNumber",        label: "AccNumber",        width: 14, sourceLiteral: "SUPPLIED" },
    { key: "AccName",          label: "AccName",          width: 50, sourceLiteral: "SUPPLIED" },
    { key: "AccCurrency",      label: "AccCurrency",      width: 12, sourceLiteral: "SUPPLIED" },
    { key: "PolicyInception",  label: "PolicyInception",  width: 16, sourceLiteral: "SUPPLIED" },
    { key: "PolicyExpiration", label: "PolicyExpiration", width: 16, sourceLiteral: "SUPPLIED" },
    { key: "ProducerName",     label: "ProducerName",     width: 30, sourceLiteral: "SUPPLIED" },
  ];
  const accRows = Object.entries(accounts).map(([name, accnum]) => ({
    AccNumber: accnum, AccName: name, AccCurrency: "USD",
    PolicyInception: policies[0]?.inception || "", PolicyExpiration: policies[0]?.expiration || "",
    ProducerName: "BirdsEyeView (CERA® AI export)",
  }));
  writeSheet(accSheet, accHeaders, accRows);

  const polSheet = wb.addWorksheet("Policy");
  const polHeaders = [
    { key: "PolicyNumber",     label: "PolicyNumber",     width: 13, sourceLiteral: "ESTIMATED" },
    { key: "AccountNumber",    label: "AccountNumber",    width: 13, sourceLiteral: "SUPPLIED" },
    { key: "PolicyName",       label: "PolicyName",       width: 50, sourceLiteral: "ESTIMATED" },
    { key: "LOB",              label: "LOB",              width: 22, sourceLiteral: "ESTIMATED" },
    { key: "InceptionDate",    label: "InceptionDate",    width: 13, sourceLiteral: "SUPPLIED" },
    { key: "ExpirationDate",   label: "ExpirationDate",   width: 13, sourceLiteral: "SUPPLIED" },
    { key: "BlanketLimit",     label: "BlanketLimit",     width: 15, kind: "money", sourceLiteral: "ESTIMATED" },
    { key: "BlanketDeductible",label: "BlanketDeductible",width: 16, kind: "money", sourceLiteral: "ESTIMATED" },
    { key: "HU_Deductible_Pct",label: "HU_Deductible_Pct",width: 14, sourceLiteral: "ESTIMATED" },
    { key: "EQ_Deductible_Pct",label: "EQ_Deductible_Pct",width: 14, sourceLiteral: "ESTIMATED" },
    { key: "PerilsCovered",    label: "PerilsCovered",    width: 22, sourceLiteral: "ESTIMATED" },
    { key: "IndemnityPeriodMonths", label: "IndemnityPeriodMonths", width: 16, sourceLiteral: "ESTIMATED" },
    { key: "ParticipationPct", label: "ParticipationPct", width: 14, sourceLiteral: "ESTIMATED" },
    { key: "Currency",         label: "Currency",         width: 10, sourceLiteral: "SUPPLIED" },
  ];
  const polRows = policies.map((p) => ({
    PolicyNumber: p.policy_number, AccountNumber: p.account_number, PolicyName: p.policy_name,
    LOB: p.lob, InceptionDate: p.inception, ExpirationDate: p.expiration,
    BlanketLimit: p.blanket_limit, BlanketDeductible: p.blanket_deductible,
    HU_Deductible_Pct: `${p.hu_deductible_pct}%`, EQ_Deductible_Pct: `${p.eq_deductible_pct}%`,
    PerilsCovered: p.perils_covered, IndemnityPeriodMonths: p.indemnity_period_m,
    ParticipationPct: `${p.participation_pct}%`, Currency: p.currency,
  }));
  writeSheet(polSheet, polHeaders, polRows);

  const locSheet = wb.addWorksheet("Location");
  const locHeaders = [
    { key: "LocNumber",        label: "LocNumber",        width: 10, sourceLiteral: "SUPPLIED" },
    { key: "AccNumber",        label: "AccNumber",        width: 10, sourceLiteral: "SUPPLIED" },
    { key: "PolicyNumber",     label: "PolicyNumber",     width: 11, sourceLiteral: "SUPPLIED" },
    { key: "LocName",          label: "LocName",          width: 32, sourceKey: "address" },
    { key: "StreetAddress",    label: "StreetAddress",    width: 26, sourceKey: "address" },
    { key: "City",             label: "City",             width: 14, sourceKey: "address" },
    { key: "AreaName",         label: "AreaName",         width: 8,  sourceKey: "address" },
    { key: "PostalCode",       label: "PostalCode",       width: 11, sourceKey: "address" },
    { key: "CountryISO",       label: "CountryISO",       width: 10, sourceKey: "address" },
    { key: "Latitude",         label: "Latitude",         width: 11, sourceKey: "latlng" },
    { key: "Longitude",        label: "Longitude",        width: 11, sourceKey: "latlng" },
    { key: "GeoMatchLevel",    label: "GeoMatchLevel",    width: 14, sourceKey: "latlng" },
    { key: "OccupancyCode",    label: "OccupancyCode",    width: 11, sourceKey: "occupancy" },
    { key: "OccupancyDesc",    label: "OccupancyDesc",    width: 28, sourceKey: "occupancy" },
    { key: "ConstructionCode", label: "ConstructionCode", width: 11, sourceKey: "construction" },
    { key: "ConstructionDesc", label: "ConstructionDesc", width: 22, sourceKey: "construction" },
    { key: "YearBuilt",        label: "YearBuilt",        width: 11, sourceKey: "year_built" },
    { key: "NumStories",       label: "NumStories",       width: 9,  sourceKey: "stories" },
    { key: "BuildingValue",    label: "BuildingValue",    width: 14, kind: "money", sourceKey: "tiv" },
    { key: "ContentsValue",    label: "ContentsValue",    width: 14, kind: "money", sourceKey: "tiv" },
    { key: "BIValue",          label: "BIValue",          width: 14, kind: "money", sourceKey: "tiv" },
    { key: "OtherValue",       label: "OtherValue",       width: 14, kind: "money", sourceKey: "tiv" },
    { key: "TIVTotal",         label: "TIVTotal",         width: 14, kind: "money", sourceKey: "tiv" },
    { key: "Currency",         label: "Currency",         width: 9,  sourceLiteral: "SUPPLIED" },
    { key: "PerilsCovered",    label: "PerilsCovered",    width: 18, sourceKey: "perils" },
    { key: "Sprinklered",      label: "Sprinklered",      width: 11, sourceKey: "sprinklered" },
    { key: "RoofType",         label: "RoofType",         width: 11, sourceKey: "other_modifiers" },
    { key: "RoofAge",          label: "RoofAge",          width: 9,  sourceKey: "other_modifiers" },
    { key: "SoftStorey",       label: "SoftStorey",       width: 11, sourceKey: "other_modifiers" },
    { key: "Basement",         label: "Basement",         width: 10, sourceKey: "other_modifiers" },
    { key: "ExtWallFinish",    label: "ExtWallFinish",    width: 13, sourceKey: "other_modifiers" },
    { key: "Source_Occupancy", label: "Source_Occupancy", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
    { key: "Source_Construction", label: "Source_Construction", width: 14, kind: "sourceFlag", headerFill: PALETTE.pink },
    { key: "Source_YearBuilt", label: "Source_YearBuilt", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
    { key: "Source_Stories",   label: "Source_Stories",   width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
    { key: "Source_Sprinklered", label: "Source_Sprinklered", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
    { key: "Source_TIV",       label: "Source_TIV",       width: 12, kind: "sourceFlag", headerFill: PALETTE.pink },
    { key: "Source_Modifiers", label: "Source_Modifiers", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
    { key: "BEV_Reasoning",    label: "CERA_AI_Reasoning", width: 50, headerFill: PALETTE.grey },
    { key: "BEV_Original_Occupancy", label: "BEV_Original_Occupancy", width: 30, headerFill: PALETTE.grey },
    { key: "BEV_Original_Construction", label: "BEV_Original_Construction", width: 30, headerFill: PALETTE.grey },
  ];
  const locRows = locations.map((loc, i) => {
    const occ = RMS_OCC[loc.occ_key] || RMS_OCC.vacant;
    const con = RMS_CONSTR[loc.constr_key] || RMS_CONSTR.unknown;
    const geo = RMS_GEO[loc.geo_canonical] || RMS_GEO.country;
    const perils = mapPerils(loc.perils_covered || [], "rms").join(",");
    return {
      LocNumber: `L${String(i + 1).padStart(4, "0")}`,
      AccNumber: loc.acc_num || "", PolicyNumber: loc.policy_number || "",
      LocName: loc.location || "", StreetAddress: loc.address || "", City: loc.city || "",
      AreaName: loc.state || "", PostalCode: loc.zip || "", CountryISO: "USA",
      Latitude: loc.lat ?? "", Longitude: loc.lng ?? "", GeoMatchLevel: `${geo.code} ${geo.desc}`,
      OccupancyCode: occ.code, OccupancyDesc: occ.desc,
      ConstructionCode: con.code, ConstructionDesc: con.desc,
      YearBuilt: loc.year_built ?? "", NumStories: loc.stories ?? "",
      BuildingValue: loc.building_value, ContentsValue: loc.contents_value,
      BIValue: loc.bi_value, OtherValue: loc.other_value, TIVTotal: loc.tiv_total,
      Currency: "USD", PerilsCovered: perils, Sprinklered: loc.sprinklered,
      RoofType: loc.roof_type, RoofAge: loc.roof_age ?? "", SoftStorey: loc.soft_storey,
      Basement: loc.basement, ExtWallFinish: loc.ext_wall,
      Source_Occupancy: loc.sources?.occupancy, Source_Construction: loc.sources?.construction,
      Source_YearBuilt: loc.sources?.year_built, Source_Stories: loc.sources?.stories,
      Source_Sprinklered: loc.sources?.sprinklered, Source_TIV: loc.sources?.tiv,
      Source_Modifiers: loc.sources?.other_modifiers,
      BEV_Reasoning: loc.class_note || "",
      BEV_Original_Occupancy: (loc.occupancy_narrative || "").slice(0, 200),
      BEV_Original_Construction: (loc.construction_narrative || "").slice(0, 200),
      __sources: loc.sources || {},
    };
  });
  writeSheet(locSheet, locHeaders, locRows, { xSplit: 3 });

  writeReadMe(wb.addWorksheet("Methodology"),
    "Methodology",
    "How every estimated field was derived",
    [
      ["1. Classifier vocabulary", "Eight occupancy keys (office, warehouse, light_mfg, heavy_mfg, food_proc, utility, civic, vacant) and seven construction keys (wood, light_metal, steel, rc, urm, mixed, unknown)."],
      ["2. Occupancy precedence", "Broker occupancy narrative, then location-name heuristic, then insured-name fallback, then vacant."],
      ["3. Construction precedence", "Broker construction narrative, then year-and-class heuristic (pre-1933 process = URM, modern food_proc = RC, etc.), then unknown."],
      ["4. TIV precedence", "Building plus Contents supplied: use as-is (SUPPLIED). Partial supply: fill missing components by class split ratio (PARTIAL). Nothing supplied: class-based notional times split ratio (ESTIMATED)."],
      ["5. Split ratios", "Office 60/25/15; Warehouse 60/30/10; Light Mfg 45/30/25; Heavy Mfg 40/30/30; Food Proc 40/30/30; Utility 40/30/30; Civic 70/20/10; Vacant 60/30/10 (Building / Contents / BI / Other)."],
      ["6. Peril coverage by state", "Geographic heuristic until policy wording supplies it. NY downstate: HU+ST+FL+WS+FR; LA/FL: HU+ST+FL+WF+FR; CA: EQ+WF+FR; IL: EQ+ST+WS+FL+FR (NMSZ); default ST+FR."],
      ["7. Secondary modifiers", "Class-based defaults for sprinkler, roof, soft-storey, basement and ext_wall when the broker did not supply. Sprinkler share 50 or above gives Y."],
      ["8. Geocode level", "Decimal-precision heuristic: 4dp or more gives rooftop (L6); 3dp gives postcode (L4); 2dp gives city (L2); else admin (L1) or country (L0)."],
      ["9. Policy structure", "One notional blanket policy per legal entity: 500M blanket limit, 1M deductible, HU 2% / EQ 5% per location, 18-month BI indemnity period. Replace with deal-record terms in production."],
    ]);

  return wb;
}

export function buildCedeWorkbook(state) {
  const { locations, accounts, policies } = state;
  if (!Array.isArray(locations) || !locations.length) throw new Error("No locations to export");
  const wb = newWorkbook();

  writeReadMe(wb.addWorksheet("ReadMe"),
    "CERA® → Verisk CEDE Export",
    "Populated Catastrophe Exposure Data Exchange template",
    [
      ["WHAT THIS FILE IS", "A Verisk CEDE-compliant exposure import for Verisk Touchstone and Touchstone Re, generated by CERA® AI from a broker schedule. Sheet names and field names follow the standard CEDE 5.x taxonomy."],
      ["HOW TO READ IT", ""],
      ["ContractInfo sheet", "One row per legal insured entity. CEDE uses Contract as the wrapper (RMS calls this Account)."],
      ["PolicyInfo sheet", "One row per notional blanket policy: LOB, dates, blanket limit and deductible, HU 2% / EQ 5%, perils covered, BI indemnity period."],
      ["LocationInfo sheet", "One row per insured location, with full AIR-coded fields, peril coverage flags using AIR codes (IF=Inland Flood, SS=Severe Storm, WT=Winter Storm), six secondary modifiers, and per-field source flags."],
      ["DataQuality sheet", "Coverage statistics, the same as the RMS file."],
      ["Methodology sheet", "How every assumption was made."],
      ["", ""],
      ["WHAT IS REAL vs ESTIMATED", ""],
      ["Pale green cells", "Value taken directly from the broker submission (SUPPLIED)."],
      ["Pale pink cells", "Value estimated by CERA® AI (ESTIMATED). Flag for underwriter review."],
      ["Pale yellow cells", "Partial: some components supplied, others derived (PARTIAL)."],
      ["Light grey cells", "Derived from supplied data by deterministic rule (DERIVED)."],
      ["", ""],
      ["KEY DIFFERENCES FROM THE RMS FILE", ""],
      ["Sheet names", "ContractInfo / LocationInfo (vs Account / Location)."],
      ["Field names", "LocationNumber, ContractID, AreaCode, Country, GeocodeLevel, ConstructionType, OccupancyType, TimeElementValue (Verisk's term for BI)."],
      ["Occupancy codes", "AIR taxonomy: 342 Office, 352 Light Mfg, 354 Food and Drug Processing, 355 Warehouse, 356 Utilities, 381 Civic."],
      ["Construction codes", "AIR taxonomy: 101 Wood, 102 Light Metal, 103 Heavy Steel, 104 RC, 106 URM."],
      ["Geocode levels", "1-5 scale (1=street/parcel, 5=country) vs RMS L0-L7."],
      ["Peril codes", "FL becomes IF (Inland Flood), ST becomes SS (Severe Storm), WS becomes WT (Winter Storm). HU/EQ/WF/FR unchanged."],
      ["", ""],
      ["CANONICAL EXPOSURE OBJECT", "This file is one of two serialisations from a single canonical exposure object. The companion RMS EDM file uses identical locations, classifications and TIV splits."],
    ]);

  writeDataQuality(wb.addWorksheet("DataQuality"), locations);

  const ctrSheet = wb.addWorksheet("ContractInfo");
  const ctrHeaders = [
    { key: "ContractID",     label: "ContractID",     width: 14, sourceLiteral: "SUPPLIED" },
    { key: "ContractName",   label: "ContractName",   width: 50, sourceLiteral: "SUPPLIED" },
    { key: "Currency",       label: "Currency",       width: 12, sourceLiteral: "SUPPLIED" },
    { key: "InceptionDate",  label: "InceptionDate",  width: 16, sourceLiteral: "SUPPLIED" },
    { key: "ExpirationDate", label: "ExpirationDate", width: 16, sourceLiteral: "SUPPLIED" },
    { key: "ProducerName",   label: "ProducerName",   width: 30, sourceLiteral: "SUPPLIED" },
  ];
  const ctrRows = Object.entries(accounts).map(([name, accnum]) => ({
    ContractID: accnum.replace("ACC", "CTR"), ContractName: name, Currency: "USD",
    InceptionDate: policies[0]?.inception || "", ExpirationDate: policies[0]?.expiration || "",
    ProducerName: "BirdsEyeView (CERA® AI export)",
  }));
  writeSheet(ctrSheet, ctrHeaders, ctrRows);

  const polSheet = wb.addWorksheet("PolicyInfo");
  const polHeaders = [
    { key: "PolicyID",         label: "PolicyID",         width: 13, sourceLiteral: "ESTIMATED" },
    { key: "ContractID",       label: "ContractID",       width: 13, sourceLiteral: "SUPPLIED" },
    { key: "PolicyName",       label: "PolicyName",       width: 50, sourceLiteral: "ESTIMATED" },
    { key: "LOB",              label: "LOB",              width: 22, sourceLiteral: "ESTIMATED" },
    { key: "InceptionDate",    label: "InceptionDate",    width: 13, sourceLiteral: "SUPPLIED" },
    { key: "ExpirationDate",   label: "ExpirationDate",   width: 13, sourceLiteral: "SUPPLIED" },
    { key: "BlanketLimit",     label: "BlanketLimit",     width: 15, kind: "money", sourceLiteral: "ESTIMATED" },
    { key: "BlanketDeductible",label: "BlanketDeductible",width: 16, kind: "money", sourceLiteral: "ESTIMATED" },
    { key: "HU_Deductible_Pct",label: "HU_Deductible_Pct",width: 14, sourceLiteral: "ESTIMATED" },
    { key: "EQ_Deductible_Pct",label: "EQ_Deductible_Pct",width: 14, sourceLiteral: "ESTIMATED" },
    { key: "PerilsCovered",    label: "PerilsCovered",    width: 22, sourceLiteral: "ESTIMATED" },
    { key: "IndemnityPeriodMonths", label: "IndemnityPeriodMonths", width: 16, sourceLiteral: "ESTIMATED" },
    { key: "ParticipationPct", label: "ParticipationPct", width: 14, sourceLiteral: "ESTIMATED" },
    { key: "Currency",         label: "Currency",         width: 10, sourceLiteral: "SUPPLIED" },
  ];
  const airPerilsCovered = "HU,EQ,IF,SS,WT,WF,FR";
  const polRows = policies.map((p) => ({
    PolicyID: p.policy_number.replace("POL", "PLY"),
    ContractID: p.account_number.replace("ACC", "CTR"),
    PolicyName: p.policy_name, LOB: p.lob, InceptionDate: p.inception, ExpirationDate: p.expiration,
    BlanketLimit: p.blanket_limit, BlanketDeductible: p.blanket_deductible,
    HU_Deductible_Pct: `${p.hu_deductible_pct}%`, EQ_Deductible_Pct: `${p.eq_deductible_pct}%`,
    PerilsCovered: airPerilsCovered, IndemnityPeriodMonths: p.indemnity_period_m,
    ParticipationPct: `${p.participation_pct}%`, Currency: p.currency,
  }));
  writeSheet(polSheet, polHeaders, polRows);

  const locSheet = wb.addWorksheet("LocationInfo");
  const locHeaders = [
    { key: "LocationNumber",   label: "LocationNumber",   width: 12, sourceLiteral: "SUPPLIED" },
    { key: "ContractID",       label: "ContractID",       width: 11, sourceLiteral: "SUPPLIED" },
    { key: "PolicyID",         label: "PolicyID",         width: 11, sourceLiteral: "SUPPLIED" },
    { key: "LocationName",     label: "LocationName",     width: 32, sourceKey: "address" },
    { key: "Address",          label: "Address",          width: 26, sourceKey: "address" },
    { key: "City",             label: "City",             width: 14, sourceKey: "address" },
    { key: "AreaCode",         label: "AreaCode",         width: 8,  sourceKey: "address" },
    { key: "PostalCode",       label: "PostalCode",       width: 11, sourceKey: "address" },
    { key: "Country",          label: "Country",          width: 10, sourceKey: "address" },
    { key: "Latitude",         label: "Latitude",         width: 11, sourceKey: "latlng" },
    { key: "Longitude",        label: "Longitude",        width: 11, sourceKey: "latlng" },
    { key: "GeocodeLevel",     label: "GeocodeLevel",     width: 14, sourceKey: "latlng" },
    { key: "OccupancyType",    label: "OccupancyType",    width: 11, sourceKey: "occupancy" },
    { key: "OccupancyDesc",    label: "OccupancyDesc",    width: 28, sourceKey: "occupancy" },
    { key: "ConstructionType", label: "ConstructionType", width: 11, sourceKey: "construction" },
    { key: "ConstructionDesc", label: "ConstructionDesc", width: 22, sourceKey: "construction" },
    { key: "YearBuilt",        label: "YearBuilt",        width: 11, sourceKey: "year_built" },
    { key: "NumStories",       label: "NumStories",       width: 9,  sourceKey: "stories" },
    { key: "BuildingValue",    label: "BuildingValue",    width: 14, kind: "money", sourceKey: "tiv" },
    { key: "ContentsValue",    label: "ContentsValue",    width: 14, kind: "money", sourceKey: "tiv" },
    { key: "TimeElementValue", label: "TimeElementValue", width: 14, kind: "money", sourceKey: "tiv" },
    { key: "OtherValue",       label: "OtherValue",       width: 14, kind: "money", sourceKey: "tiv" },
    { key: "TIVTotal",         label: "TIVTotal",         width: 14, kind: "money", sourceKey: "tiv" },
    { key: "Currency",         label: "Currency",         width: 9,  sourceLiteral: "SUPPLIED" },
    { key: "PerilsCovered",    label: "PerilsCovered",    width: 18, sourceKey: "perils" },
    { key: "Sprinklered",      label: "Sprinklered",      width: 11, sourceKey: "sprinklered" },
    { key: "RoofType",         label: "RoofType",         width: 11, sourceKey: "other_modifiers" },
    { key: "RoofAge",          label: "RoofAge",          width: 9,  sourceKey: "other_modifiers" },
    { key: "SoftStorey",       label: "SoftStorey",       width: 11, sourceKey: "other_modifiers" },
    { key: "Basement",         label: "Basement",         width: 10, sourceKey: "other_modifiers" },
    { key: "ExtWallFinish",    label: "ExtWallFinish",    width: 13, sourceKey: "other_modifiers" },
    { key: "Source_Occupancy", label: "Source_Occupancy", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
    { key: "Source_Construction", label: "Source_Construction", width: 14, kind: "sourceFlag", headerFill: PALETTE.pink },
    { key: "Source_YearBuilt", label: "Source_YearBuilt", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
    { key: "Source_Stories",   label: "Source_Stories",   width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
    { key: "Source_Sprinklered", label: "Source_Sprinklered", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
    { key: "Source_TIV",       label: "Source_TIV",       width: 12, kind: "sourceFlag", headerFill: PALETTE.pink },
    { key: "Source_Modifiers", label: "Source_Modifiers", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
    { key: "BEV_Reasoning",    label: "CERA_AI_Reasoning", width: 50, headerFill: PALETTE.grey },
    { key: "BEV_Original_Occupancy", label: "BEV_Original_Occupancy", width: 30, headerFill: PALETTE.grey },
    { key: "BEV_Original_Construction", label: "BEV_Original_Construction", width: 30, headerFill: PALETTE.grey },
  ];
  const locRows = locations.map((loc, i) => {
    const occ = AIR_OCC[loc.occ_key] || AIR_OCC.vacant;
    const con = AIR_CONSTR[loc.constr_key] || AIR_CONSTR.unknown;
    const geo = AIR_GEO[loc.geo_canonical] || AIR_GEO.country;
    const perils = mapPerils(loc.perils_covered || [], "cede").join(",");
    return {
      LocationNumber: `L${String(i + 1).padStart(4, "0")}`,
      ContractID: (loc.acc_num || "").replace("ACC", "CTR"),
      PolicyID: (loc.policy_number || "").replace("POL", "PLY"),
      LocationName: loc.location || "", Address: loc.address || "", City: loc.city || "",
      AreaCode: loc.state || "", PostalCode: loc.zip || "", Country: "US",
      Latitude: loc.lat ?? "", Longitude: loc.lng ?? "", GeocodeLevel: `${geo.code} ${geo.desc}`,
      OccupancyType: occ.code, OccupancyDesc: occ.desc,
      ConstructionType: con.code, ConstructionDesc: con.desc,
      YearBuilt: loc.year_built ?? "", NumStories: loc.stories ?? "",
      BuildingValue: loc.building_value, ContentsValue: loc.contents_value,
      TimeElementValue: loc.bi_value, OtherValue: loc.other_value, TIVTotal: loc.tiv_total,
      Currency: "USD", PerilsCovered: perils, Sprinklered: loc.sprinklered,
      RoofType: loc.roof_type, RoofAge: loc.roof_age ?? "", SoftStorey: loc.soft_storey,
      Basement: loc.basement, ExtWallFinish: loc.ext_wall,
      Source_Occupancy: loc.sources?.occupancy, Source_Construction: loc.sources?.construction,
      Source_YearBuilt: loc.sources?.year_built, Source_Stories: loc.sources?.stories,
      Source_Sprinklered: loc.sources?.sprinklered, Source_TIV: loc.sources?.tiv,
      Source_Modifiers: loc.sources?.other_modifiers,
      BEV_Reasoning: loc.class_note || "",
      BEV_Original_Occupancy: (loc.occupancy_narrative || "").slice(0, 200),
      BEV_Original_Construction: (loc.construction_narrative || "").slice(0, 200),
      __sources: loc.sources || {},
    };
  });
  writeSheet(locSheet, locHeaders, locRows, { xSplit: 3 });

  writeReadMe(wb.addWorksheet("Methodology"),
    "Methodology",
    "How every estimated field was derived",
    [
      ["1. Classifier vocabulary", "Eight occupancy keys and seven construction keys. Identical to the companion RMS EDM export's vocabulary; only the AIR code crosswalk differs."],
      ["2. Occupancy precedence", "Broker narrative, then location-name heuristic, then insured-name fallback, then vacant."],
      ["3. Construction precedence", "Broker narrative, then year-and-class heuristic, then unknown. Compound percentage descriptions resolved by predominant class."],
      ["4. TIV precedence", "Building plus Contents supplied: use as-is. Partial: fill missing components by class split ratio. Nothing supplied: class-based notional times split ratio."],
      ["5. Split ratios", "Office 60/25/15; Warehouse 60/30/10; Light Mfg 45/30/25; Heavy Mfg 40/30/30; Food Proc 40/30/30; Utility 40/30/30; Civic 70/20/10; Vacant 60/30/10."],
      ["6. Peril coverage by state", "Same geographic heuristic as the RMS file. AIR-specific letter codes applied at serialisation: FL becomes IF, ST becomes SS, WS becomes WT."],
      ["7. Secondary modifiers", "Class-based defaults when the broker did not supply. Sprinkler share 50 or above gives Y."],
      ["8. Geocode level", "1 = street/parcel, 2 = postcode, 4 = city/admin, 5 = country."],
      ["9. Policy structure", "One notional blanket policy per legal entity: 500M limit, 1M deductible, HU 2% / EQ 5% per location, 18-month BI."],
    ]);

  return wb;
}

export async function downloadWorkbook(wb, filename) {
  const buffer = await wb.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(a.href);
}
