// POST /api/export-cede
// Body: { locations, accounts, policies }
// Returns: xlsx binary stream styled in Verisk CEDE format.

import ExcelJS from "exceljs";
import { AIR_OCC, AIR_CONSTR, AIR_GEO } from "../../shared/cede-codes.mjs";
import { mapPerils } from "../../shared/canonical.mjs";
import { writeReadMe, writeSheet, writeDataQuality } from "../../shared/exporter-common.mjs";
import { PALETTE } from "../../shared/palette.mjs";

export const handler = async (event) => {
  if (event.httpMethod !== "POST") return { statusCode: 405, body: "Method not allowed" };
  try {
    const { locations, accounts, policies } = JSON.parse(event.body || "{}");
    if (!Array.isArray(locations) || !locations.length) {
      return { statusCode: 400, body: "Missing locations[]" };
    }

    const wb = new ExcelJS.Workbook();
    wb.creator = "CERA® AI — EDM & CEDE Converter";
    wb.created = new Date();

    // ---------- ReadMe ----------
    writeReadMe(wb.addWorksheet("ReadMe"),
      "CERA® → Verisk CEDE Export",
      "Populated Catastrophe Exposure Data Exchange template",
      [
        ["WHAT THIS FILE IS", "A Verisk CEDE-compliant exposure import for Verisk Touchstone / Touchstone Re, generated by CERA® AI from a broker schedule. Sheet names and field names follow the standard CEDE 5.x taxonomy."],
        ["HOW TO READ IT", ""],
        ["ContractInfo sheet", "One row per legal insured entity. CEDE uses Contract as the wrapper (RMS calls this Account)."],
        ["PolicyInfo sheet", "One row per notional blanket policy — LOB, dates, blanket limit/deductible, HU 2% / EQ 5%, perils covered, BI indemnity period."],
        ["LocationInfo sheet", "One row per insured location, with full AIR-coded fields, peril coverage flags using AIR codes (IF=Inland Flood, SS=Severe Storm, WT=Winter Storm), six secondary modifiers, and per-field source flags."],
        ["DataQuality sheet", "Coverage statistics — same as the RMS file."],
        ["Methodology sheet", "How every assumption was made."],
        ["", ""],
        ["WHAT IS REAL vs. ESTIMATED", ""],
        ["Pale green cells", "Value taken directly from the broker submission (SUPPLIED)."],
        ["Pale pink cells", "Value estimated by CERA® AI (ESTIMATED) — flag for underwriter review."],
        ["Pale yellow cells", "Partial — some components supplied, others derived (PARTIAL)."],
        ["Light grey cells", "Derived from supplied data by deterministic rule (DERIVED)."],
        ["", ""],
        ["KEY DIFFERENCES FROM THE RMS FILE", ""],
        ["Sheet names", "ContractInfo / LocationInfo (vs. Account / Location)."],
        ["Field names", "LocationNumber, ContractID, AreaCode, Country, GeocodeLevel, ConstructionType, OccupancyType, TimeElementValue (Verisk's term for BI)."],
        ["Occupancy codes", "AIR taxonomy — 342 Office, 352 Light Mfg, 354 Food and Drug Processing, 355 Warehouse, 356 Utilities, 381 Civic."],
        ["Construction codes", "AIR taxonomy — 101 Wood, 102 Light Metal, 103 Heavy Steel, 104 RC, 106 URM."],
        ["Geocode levels", "1-5 scale (1=street/parcel, 5=country) — vs. RMS L0-L7."],
        ["Peril codes", "FL→IF (Inland Flood), ST→SS (Severe Storm), WS→WT (Winter Storm). HU/EQ/WF/FR unchanged."],
        ["", ""],
        ["CANONICAL EXPOSURE OBJECT", "This file is one of two serialisations from a single canonical exposure object. The companion RMS EDM file uses identical locations, classifications, and TIV splits."],
      ]);

    // ---------- DataQuality ----------
    writeDataQuality(wb.addWorksheet("DataQuality"), locations);

    // ---------- ContractInfo ----------
    const ctrSheet = wb.addWorksheet("ContractInfo");
    const ctrHeaders = [
      { key: "ContractID",     label: "ContractID",     width: 14, sourceLiteral: "SUPPLIED" },
      { key: "ContractName",   label: "ContractName",   width: 50, sourceLiteral: "SUPPLIED" },
      { key: "Currency",       label: "Currency",       width: 12, sourceLiteral: "SUPPLIED" },
      { key: "InceptionDate",  label: "InceptionDate",  width: 16, sourceLiteral: "SUPPLIED" },
      { key: "ExpirationDate", label: "ExpirationDate", width: 16, sourceLiteral: "SUPPLIED" },
      { key: "ProducerName",   label: "ProducerName",   width: 30, sourceLiteral: "SUPPLIED" },
    ];
    const ctrRows = Object.entries(accounts).map(([name, accnum]) => ({
      ContractID: accnum.replace("ACC", "CTR"),
      ContractName: name, Currency: "USD",
      InceptionDate: policies[0]?.inception || "",
      ExpirationDate: policies[0]?.expiration || "",
      ProducerName: "BirdsEyeView (CERA® AI export)",
    }));
    writeSheet(ctrSheet, ctrHeaders, ctrRows);

    // ---------- PolicyInfo ----------
    const polSheet = wb.addWorksheet("PolicyInfo");
    const polHeaders = [
      { key: "PolicyID",         label: "PolicyID",         width: 13, sourceLiteral: "ESTIMATED" },
      { key: "ContractID",       label: "ContractID",       width: 13, sourceLiteral: "SUPPLIED" },
      { key: "PolicyName",       label: "PolicyName",       width: 50, sourceLiteral: "ESTIMATED" },
      { key: "LOB",              label: "LOB",              width: 22, sourceLiteral: "ESTIMATED" },
      { key: "InceptionDate",    label: "InceptionDate",    width: 13, sourceLiteral: "SUPPLIED" },
      { key: "ExpirationDate",   label: "ExpirationDate",   width: 13, sourceLiteral: "SUPPLIED" },
      { key: "BlanketLimit",     label: "BlanketLimit",     width: 15, kind: "money", sourceLiteral: "ESTIMATED" },
      { key: "BlanketDeductible",label: "BlanketDeductible",width: 16, kind: "money", sourceLiteral: "ESTIMATED" },
      { key: "HU_Deductible_Pct",label: "HU_Deductible_Pct",width: 14, sourceLiteral: "ESTIMATED" },
      { key: "EQ_Deductible_Pct",label: "EQ_Deductible_Pct",width: 14, sourceLiteral: "ESTIMATED" },
      { key: "PerilsCovered",    label: "PerilsCovered",    width: 22, sourceLiteral: "ESTIMATED" },
      { key: "IndemnityPeriodMonths", label: "IndemnityPeriodMonths", width: 16, sourceLiteral: "ESTIMATED" },
      { key: "ParticipationPct", label: "ParticipationPct", width: 14, sourceLiteral: "ESTIMATED" },
      { key: "Currency",         label: "Currency",         width: 10, sourceLiteral: "SUPPLIED" },
    ];
    const airPerilsCovered = "HU,EQ,IF,SS,WT,WF,FR";
    const polRows = policies.map((p) => ({
      PolicyID: p.policy_number.replace("POL", "PLY"),
      ContractID: p.account_number.replace("ACC", "CTR"),
      PolicyName: p.policy_name, LOB: p.lob, InceptionDate: p.inception, ExpirationDate: p.expiration,
      BlanketLimit: p.blanket_limit, BlanketDeductible: p.blanket_deductible,
      HU_Deductible_Pct: `${p.hu_deductible_pct}%`, EQ_Deductible_Pct: `${p.eq_deductible_pct}%`,
      PerilsCovered: airPerilsCovered, IndemnityPeriodMonths: p.indemnity_period_m,
      ParticipationPct: `${p.participation_pct}%`, Currency: p.currency,
    }));
    writeSheet(polSheet, polHeaders, polRows);

    // ---------- LocationInfo ----------
    const locSheet = wb.addWorksheet("LocationInfo");
    const locHeaders = [
      { key: "LocationNumber",   label: "LocationNumber",   width: 12, sourceLiteral: "SUPPLIED" },
      { key: "ContractID",       label: "ContractID",       width: 11, sourceLiteral: "SUPPLIED" },
      { key: "PolicyID",         label: "PolicyID",         width: 11, sourceLiteral: "SUPPLIED" },
      { key: "LocationName",     label: "LocationName",     width: 32, sourceKey: "address" },
      { key: "Address",          label: "Address",          width: 26, sourceKey: "address" },
      { key: "City",             label: "City",             width: 14, sourceKey: "address" },
      { key: "AreaCode",         label: "AreaCode",         width: 8,  sourceKey: "address" },
      { key: "PostalCode",       label: "PostalCode",       width: 11, sourceKey: "address" },
      { key: "Country",          label: "Country",          width: 10, sourceKey: "address" },
      { key: "Latitude",         label: "Latitude",         width: 11, sourceKey: "latlng" },
      { key: "Longitude",        label: "Longitude",        width: 11, sourceKey: "latlng" },
      { key: "GeocodeLevel",     label: "GeocodeLevel",     width: 14, sourceKey: "latlng" },
      { key: "OccupancyType",    label: "OccupancyType",    width: 11, sourceKey: "occupancy" },
      { key: "OccupancyDesc",    label: "OccupancyDesc",    width: 28, sourceKey: "occupancy" },
      { key: "ConstructionType", label: "ConstructionType", width: 11, sourceKey: "construction" },
      { key: "ConstructionDesc", label: "ConstructionDesc", width: 22, sourceKey: "construction" },
      { key: "YearBuilt",        label: "YearBuilt",        width: 11, sourceKey: "year_built" },
      { key: "NumStories",       label: "NumStories",       width: 9,  sourceKey: "stories" },
      { key: "BuildingValue",    label: "BuildingValue",    width: 14, kind: "money", sourceKey: "tiv" },
      { key: "ContentsValue",    label: "ContentsValue",    width: 14, kind: "money", sourceKey: "tiv" },
      { key: "TimeElementValue", label: "TimeElementValue", width: 14, kind: "money", sourceKey: "tiv" },
      { key: "OtherValue",       label: "OtherValue",       width: 14, kind: "money", sourceKey: "tiv" },
      { key: "TIVTotal",         label: "TIVTotal",         width: 14, kind: "money", sourceKey: "tiv" },
      { key: "Currency",         label: "Currency",         width: 9,  sourceLiteral: "SUPPLIED" },
      { key: "PerilsCovered",    label: "PerilsCovered",    width: 18, sourceKey: "perils" },
      { key: "Sprinklered",      label: "Sprinklered",      width: 11, sourceKey: "sprinklered" },
      { key: "RoofType",         label: "RoofType",         width: 11, sourceKey: "other_modifiers" },
      { key: "RoofAge",          label: "RoofAge",          width: 9,  sourceKey: "other_modifiers" },
      { key: "SoftStorey",       label: "SoftStorey",       width: 11, sourceKey: "other_modifiers" },
      { key: "Basement",         label: "Basement",         width: 10, sourceKey: "other_modifiers" },
      { key: "ExtWallFinish",    label: "ExtWallFinish",    width: 13, sourceKey: "other_modifiers" },
      { key: "Source_Occupancy", label: "Source_Occupancy", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
      { key: "Source_Construction", label: "Source_Construction", width: 14, kind: "sourceFlag", headerFill: PALETTE.pink },
      { key: "Source_YearBuilt", label: "Source_YearBuilt", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
      { key: "Source_Stories",   label: "Source_Stories",   width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
      { key: "Source_Sprinklered", label: "Source_Sprinklered", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
      { key: "Source_TIV",       label: "Source_TIV",       width: 12, kind: "sourceFlag", headerFill: PALETTE.pink },
      { key: "Source_Modifiers", label: "Source_Modifiers", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
      { key: "BEV_Reasoning",    label: "CERA_AI_Reasoning", width: 50, headerFill: PALETTE.grey },
      { key: "BEV_Original_Occupancy", label: "BEV_Original_Occupancy", width: 30, headerFill: PALETTE.grey },
      { key: "BEV_Original_Construction", label: "BEV_Original_Construction", width: 30, headerFill: PALETTE.grey },
    ];

    const locRows = locations.map((loc, i) => {
      const occ = AIR_OCC[loc.occ_key] || AIR_OCC.vacant;
      const con = AIR_CONSTR[loc.constr_key] || AIR_CONSTR.unknown;
      const geo = AIR_GEO[loc.geo_canonical] || AIR_GEO.country;
      const perils = mapPerils(loc.perils_covered || [], "cede").join(",");
      return {
        LocationNumber: `L${String(i + 1).padStart(4, "0")}`,
        ContractID: (loc.acc_num || "").replace("ACC", "CTR"),
        PolicyID: (loc.policy_number || "").replace("POL", "PLY"),
        LocationName: loc.location || "",
        Address: loc.address || "",
        City: loc.city || "",
        AreaCode: loc.state || "",
        PostalCode: loc.zip || "",
        Country: "US",
        Latitude: loc.lat ?? "",
        Longitude: loc.lng ?? "",
        GeocodeLevel: `${geo.code} — ${geo.desc}`,
        OccupancyType: occ.code,
        OccupancyDesc: occ.desc,
        ConstructionType: con.code,
        ConstructionDesc: con.desc,
        YearBuilt: loc.year_built ?? "",
        NumStories: loc.stories ?? "",
        BuildingValue: loc.building_value,
        ContentsValue: loc.contents_value,
        TimeElementValue: loc.bi_value,
        OtherValue: loc.other_value,
        TIVTotal: loc.tiv_total,
        Currency: "USD",
        PerilsCovered: perils,
        Sprinklered: loc.sprinklered,
        RoofType: loc.roof_type,
        RoofAge: loc.roof_age ?? "",
        SoftStorey: loc.soft_storey,
        Basement: loc.basement,
        ExtWallFinish: loc.ext_wall,
        Source_Occupancy: loc.sources?.occupancy,
        Source_Construction: loc.sources?.construction,
        Source_YearBuilt: loc.sources?.year_built,
        Source_Stories: loc.sources?.stories,
        Source_Sprinklered: loc.sources?.sprinklered,
        Source_TIV: loc.sources?.tiv,
        Source_Modifiers: loc.sources?.other_modifiers,
        BEV_Reasoning: loc.class_note || "",
        BEV_Original_Occupancy: (loc.occupancy_narrative || "").slice(0, 200),
        BEV_Original_Construction: (loc.construction_narrative || "").slice(0, 200),
        __sources: loc.sources || {},
      };
    });
    writeSheet(locSheet, locHeaders, locRows, { xSplit: 3 });

    // ---------- Methodology ----------
    writeReadMe(wb.addWorksheet("Methodology"),
      "Methodology",
      "How every estimated field was derived",
      [
        ["1. Classifier vocabulary", "Eight occupancy keys and seven construction keys, constrained via CERA® AI schema enforcement. Identical to the companion RMS EDM export's vocabulary — only the AIR code crosswalk differs."],
        ["2. Occupancy precedence", "Broker narrative > location-name heuristic > insured-name fallback > 'vacant'."],
        ["3. Construction precedence", "Broker narrative > year-and-class heuristic > 'unknown'. Compound % descriptions resolved by predominant class."],
        ["4. TIV precedence", "Building + Contents supplied → use as-is. Partial → fill missing components by class split ratio. Nothing supplied → class-based notional × split ratio."],
        ["5. Split ratios", "Office 60/25/15; Warehouse 60/30/10; Light Mfg 45/30/25; Heavy Mfg 40/30/30; Food Proc 40/30/30; Utility 40/30/30; Civic 70/20/10; Vacant 60/30/10."],
        ["6. Peril coverage by state", "Same geographic heuristic as the RMS file. AIR-specific letter codes applied at serialisation: FL→IF, ST→SS, WS→WT."],
        ["7. Secondary modifiers", "Class-based defaults when broker did not supply. Sprinkler % >= 50 → 'Y'."],
        ["8. Geocode level", "1 = street/parcel, 2 = postcode, 4 = city/admin, 5 = country."],
        ["9. Policy structure", "One notional blanket policy per legal entity: $500M limit, $1M deductible, HU 2% / EQ 5% per-loc, 18-month BI."],
      ]);

    const buffer = await wb.xlsx.writeBuffer();
    return {
      statusCode: 200,
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "Content-Disposition": 'attachment; filename="CERA-Verisk-CEDE-Export.xlsx"',
      },
      body: Buffer.from(buffer).toString("base64"),
      isBase64Encoded: true,
    };
  } catch (err) {
    return { statusCode: 500, body: `export-cede error: ${err.message}` };
  }
};
