// POST /api/export-edm
// Body: { locations, accounts, policies, opts? }
// Returns: xlsx binary stream styled in RMS EDM (MRI) format.

import ExcelJS from "exceljs";
import { RMS_OCC, RMS_CONSTR, RMS_GEO } from "../../shared/rms-codes.mjs";
import { mapPerils } from "../../shared/canonical.mjs";
import { writeReadMe, writeSheet, writeDataQuality } from "../../shared/exporter-common.mjs";
import { PALETTE } from "../../shared/palette.mjs";

export const handler = async (event) => {
  if (event.httpMethod !== "POST") return { statusCode: 405, body: "Method not allowed" };
  try {
    const { locations, accounts, policies } = JSON.parse(event.body || "{}");
    if (!Array.isArray(locations) || !locations.length) {
      return { statusCode: 400, body: "Missing locations[]" };
    }

    const wb = new ExcelJS.Workbook();
    wb.creator = "CERA® AI — EDM & CEDE Converter";
    wb.created = new Date();

    // ---------- ReadMe ----------
    writeReadMe(wb.addWorksheet("ReadMe"),
      "CERA® → RMS EDM (MRI) Export",
      "Populated Moody's RMS EDM import template",
      [
        ["WHAT THIS FILE IS", "An MRI-compatible exposure import for Moody's RMS Risk Modeler 2.0, generated by CERA® AI from a broker schedule. Sheet names and field names follow the standard RMS taxonomy."],
        ["HOW TO READ IT", ""],
        ["Account sheet", "One row per legal insured entity. RMS treats accounts as the wrapper for one or more policies."],
        ["Policy sheet", "One row per notional blanket policy — LOB, dates, blanket limit/deductible, HU 2% / EQ 5% deductibles, perils covered, BI indemnity period."],
        ["Location sheet", "One row per insured location, with full RMS-coded fields (occupancy, construction, geocode level), per-state peril coverage, six secondary modifiers, and per-field source flags."],
        ["DataQuality sheet", "Coverage statistics: how many rows had each field supplied by the broker vs estimated by CERA® AI."],
        ["Methodology sheet", "How every assumption was made — classifier vocabulary, TIV split ratios, peril coverage by state, secondary modifier defaults."],
        ["", ""],
        ["WHAT IS REAL vs. ESTIMATED", ""],
        ["Pale green cells", "Value taken directly from the broker submission (SUPPLIED)."],
        ["Pale pink cells", "Value estimated by CERA® AI (ESTIMATED) — flag for underwriter review."],
        ["Pale yellow cells", "Partial — some components supplied, others derived from split ratios (PARTIAL)."],
        ["Light grey cells", "Derived from supplied data by deterministic rule (DERIVED) — e.g. peril coverage from state."],
        ["", ""],
        ["CODE TAXONOMIES", "Occupancy and construction codes shown follow standard RMS code dictionaries (322 General Office, 343 Industrial Warehouse, 344 Food & Drug Processing, 121 Reinforced Concrete, 132 URM, etc.). Production exports can be cross-walked to the exact RM-version codes your Risk Modeler instance expects."],
        ["CANONICAL EXPOSURE OBJECT", "This file is one of two serialisations from a single canonical exposure object. The companion Verisk CEDE file uses identical locations, classifications, and TIV splits — only the code dictionaries, sheet names, and geocode taxonomy differ."],
      ]);

    // ---------- DataQuality ----------
    writeDataQuality(wb.addWorksheet("DataQuality"), locations);

    // ---------- Account ----------
    const accSheet = wb.addWorksheet("Account");
    const accHeaders = [
      { key: "AccNumber",        label: "AccNumber",        width: 14, sourceLiteral: "SUPPLIED" },
      { key: "AccName",          label: "AccName",          width: 50, sourceLiteral: "SUPPLIED" },
      { key: "AccCurrency",      label: "AccCurrency",      width: 12, sourceLiteral: "SUPPLIED" },
      { key: "PolicyInception",  label: "PolicyInception",  width: 16, sourceLiteral: "SUPPLIED" },
      { key: "PolicyExpiration", label: "PolicyExpiration", width: 16, sourceLiteral: "SUPPLIED" },
      { key: "ProducerName",     label: "ProducerName",     width: 30, sourceLiteral: "SUPPLIED" },
    ];
    const accRows = Object.entries(accounts).map(([name, accnum]) => ({
      AccNumber: accnum, AccName: name, AccCurrency: "USD",
      PolicyInception: policies[0]?.inception || "", PolicyExpiration: policies[0]?.expiration || "",
      ProducerName: "BirdsEyeView (CERA® AI export)",
    }));
    writeSheet(accSheet, accHeaders, accRows);

    // ---------- Policy ----------
    const polSheet = wb.addWorksheet("Policy");
    const polHeaders = [
      { key: "PolicyNumber",     label: "PolicyNumber",     width: 13, sourceLiteral: "ESTIMATED" },
      { key: "AccountNumber",    label: "AccountNumber",    width: 13, sourceLiteral: "SUPPLIED" },
      { key: "PolicyName",       label: "PolicyName",       width: 50, sourceLiteral: "ESTIMATED" },
      { key: "LOB",              label: "LOB",              width: 22, sourceLiteral: "ESTIMATED" },
      { key: "InceptionDate",    label: "InceptionDate",    width: 13, sourceLiteral: "SUPPLIED" },
      { key: "ExpirationDate",   label: "ExpirationDate",   width: 13, sourceLiteral: "SUPPLIED" },
      { key: "BlanketLimit",     label: "BlanketLimit",     width: 15, kind: "money", sourceLiteral: "ESTIMATED" },
      { key: "BlanketDeductible",label: "BlanketDeductible",width: 16, kind: "money", sourceLiteral: "ESTIMATED" },
      { key: "HU_Deductible_Pct",label: "HU_Deductible_Pct",width: 14, sourceLiteral: "ESTIMATED" },
      { key: "EQ_Deductible_Pct",label: "EQ_Deductible_Pct",width: 14, sourceLiteral: "ESTIMATED" },
      { key: "PerilsCovered",    label: "PerilsCovered",    width: 22, sourceLiteral: "ESTIMATED" },
      { key: "IndemnityPeriodMonths", label: "IndemnityPeriodMonths", width: 16, sourceLiteral: "ESTIMATED" },
      { key: "ParticipationPct", label: "ParticipationPct", width: 14, sourceLiteral: "ESTIMATED" },
      { key: "Currency",         label: "Currency",         width: 10, sourceLiteral: "SUPPLIED" },
    ];
    const polRows = policies.map((p) => ({
      PolicyNumber: p.policy_number, AccountNumber: p.account_number, PolicyName: p.policy_name,
      LOB: p.lob, InceptionDate: p.inception, ExpirationDate: p.expiration,
      BlanketLimit: p.blanket_limit, BlanketDeductible: p.blanket_deductible,
      HU_Deductible_Pct: `${p.hu_deductible_pct}%`, EQ_Deductible_Pct: `${p.eq_deductible_pct}%`,
      PerilsCovered: p.perils_covered, IndemnityPeriodMonths: p.indemnity_period_m,
      ParticipationPct: `${p.participation_pct}%`, Currency: p.currency,
    }));
    writeSheet(polSheet, polHeaders, polRows);

    // ---------- Location ----------
    const locSheet = wb.addWorksheet("Location");
    const locHeaders = [
      { key: "LocNumber",        label: "LocNumber",        width: 10, sourceLiteral: "SUPPLIED" },
      { key: "AccNumber",        label: "AccNumber",        width: 10, sourceLiteral: "SUPPLIED" },
      { key: "PolicyNumber",     label: "PolicyNumber",     width: 11, sourceLiteral: "SUPPLIED" },
      { key: "LocName",          label: "LocName",          width: 32, sourceKey: "address" },
      { key: "StreetAddress",    label: "StreetAddress",    width: 26, sourceKey: "address" },
      { key: "City",             label: "City",             width: 14, sourceKey: "address" },
      { key: "AreaName",         label: "AreaName",         width: 8,  sourceKey: "address" },
      { key: "PostalCode",       label: "PostalCode",       width: 11, sourceKey: "address" },
      { key: "CountryISO",       label: "CountryISO",       width: 10, sourceKey: "address" },
      { key: "Latitude",         label: "Latitude",         width: 11, sourceKey: "latlng" },
      { key: "Longitude",        label: "Longitude",        width: 11, sourceKey: "latlng" },
      { key: "GeoMatchLevel",    label: "GeoMatchLevel",    width: 14, sourceKey: "latlng" },
      { key: "OccupancyCode",    label: "OccupancyCode",    width: 11, sourceKey: "occupancy" },
      { key: "OccupancyDesc",    label: "OccupancyDesc",    width: 28, sourceKey: "occupancy" },
      { key: "ConstructionCode", label: "ConstructionCode", width: 11, sourceKey: "construction" },
      { key: "ConstructionDesc", label: "ConstructionDesc", width: 22, sourceKey: "construction" },
      { key: "YearBuilt",        label: "YearBuilt",        width: 11, sourceKey: "year_built" },
      { key: "NumStories",       label: "NumStories",       width: 9,  sourceKey: "stories" },
      { key: "BuildingValue",    label: "BuildingValue",    width: 14, kind: "money", sourceKey: "tiv" },
      { key: "ContentsValue",    label: "ContentsValue",    width: 14, kind: "money", sourceKey: "tiv" },
      { key: "BIValue",          label: "BIValue",          width: 14, kind: "money", sourceKey: "tiv" },
      { key: "OtherValue",       label: "OtherValue",       width: 14, kind: "money", sourceKey: "tiv" },
      { key: "TIVTotal",         label: "TIVTotal",         width: 14, kind: "money", sourceKey: "tiv" },
      { key: "Currency",         label: "Currency",         width: 9,  sourceLiteral: "SUPPLIED" },
      { key: "PerilsCovered",    label: "PerilsCovered",    width: 18, sourceKey: "perils" },
      { key: "Sprinklered",      label: "Sprinklered",      width: 11, sourceKey: "sprinklered" },
      { key: "RoofType",         label: "RoofType",         width: 11, sourceKey: "other_modifiers" },
      { key: "RoofAge",          label: "RoofAge",          width: 9,  sourceKey: "other_modifiers" },
      { key: "SoftStorey",       label: "SoftStorey",       width: 11, sourceKey: "other_modifiers" },
      { key: "Basement",         label: "Basement",         width: 10, sourceKey: "other_modifiers" },
      { key: "ExtWallFinish",    label: "ExtWallFinish",    width: 13, sourceKey: "other_modifiers" },
      { key: "Source_Occupancy", label: "Source_Occupancy", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
      { key: "Source_Construction", label: "Source_Construction", width: 14, kind: "sourceFlag", headerFill: PALETTE.pink },
      { key: "Source_YearBuilt", label: "Source_YearBuilt", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
      { key: "Source_Stories",   label: "Source_Stories",   width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
      { key: "Source_Sprinklered", label: "Source_Sprinklered", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
      { key: "Source_TIV",       label: "Source_TIV",       width: 12, kind: "sourceFlag", headerFill: PALETTE.pink },
      { key: "Source_Modifiers", label: "Source_Modifiers", width: 13, kind: "sourceFlag", headerFill: PALETTE.pink },
      { key: "BEV_Reasoning",    label: "CERA_AI_Reasoning", width: 50, headerFill: PALETTE.grey },
      { key: "BEV_Original_Occupancy", label: "BEV_Original_Occupancy", width: 30, headerFill: PALETTE.grey },
      { key: "BEV_Original_Construction", label: "BEV_Original_Construction", width: 30, headerFill: PALETTE.grey },
    ];

    const locRows = locations.map((loc, i) => {
      const occ = RMS_OCC[loc.occ_key] || RMS_OCC.vacant;
      const con = RMS_CONSTR[loc.constr_key] || RMS_CONSTR.unknown;
      const geo = RMS_GEO[loc.geo_canonical] || RMS_GEO.country;
      const perils = mapPerils(loc.perils_covered || [], "rms").join(",");
      return {
        LocNumber: `L${String(i + 1).padStart(4, "0")}`,
        AccNumber: loc.acc_num || "",
        PolicyNumber: loc.policy_number || "",
        LocName: loc.location || "",
        StreetAddress: loc.address || "",
        City: loc.city || "",
        AreaName: loc.state || "",
        PostalCode: loc.zip || "",
        CountryISO: "USA",
        Latitude: loc.lat ?? "",
        Longitude: loc.lng ?? "",
        GeoMatchLevel: `${geo.code} — ${geo.desc}`,
        OccupancyCode: occ.code,
        OccupancyDesc: occ.desc,
        ConstructionCode: con.code,
        ConstructionDesc: con.desc,
        YearBuilt: loc.year_built ?? "",
        NumStories: loc.stories ?? "",
        BuildingValue: loc.building_value,
        ContentsValue: loc.contents_value,
        BIValue: loc.bi_value,
        OtherValue: loc.other_value,
        TIVTotal: loc.tiv_total,
        Currency: "USD",
        PerilsCovered: perils,
        Sprinklered: loc.sprinklered,
        RoofType: loc.roof_type,
        RoofAge: loc.roof_age ?? "",
        SoftStorey: loc.soft_storey,
        Basement: loc.basement,
        ExtWallFinish: loc.ext_wall,
        Source_Occupancy: loc.sources?.occupancy,
        Source_Construction: loc.sources?.construction,
        Source_YearBuilt: loc.sources?.year_built,
        Source_Stories: loc.sources?.stories,
        Source_Sprinklered: loc.sources?.sprinklered,
        Source_TIV: loc.sources?.tiv,
        Source_Modifiers: loc.sources?.other_modifiers,
        BEV_Reasoning: loc.class_note || "",
        BEV_Original_Occupancy: (loc.occupancy_narrative || "").slice(0, 200),
        BEV_Original_Construction: (loc.construction_narrative || "").slice(0, 200),
        __sources: loc.sources || {},
      };
    });
    writeSheet(locSheet, locHeaders, locRows, { xSplit: 3 });

    // ---------- Methodology ----------
    writeReadMe(wb.addWorksheet("Methodology"),
      "Methodology",
      "How every estimated field was derived",
      [
        ["1. Classifier vocabulary", "Eight occupancy keys (office, warehouse, light_mfg, heavy_mfg, food_proc, utility, civic, vacant) and seven construction keys (wood, light_metal, steel, rc, urm, mixed, unknown). All CERA® AI classifications are constrained to this vocabulary via schema enforcement."],
        ["2. Occupancy precedence", "Broker occupancy narrative > location-name heuristic > insured-name fallback > 'vacant'. Where broker narrative resolves cleanly via deterministic rule, CERA® AI is not invoked (saves cost, fully deterministic)."],
        ["3. Construction precedence", "Broker construction narrative > year-and-class heuristic (pre-1933 process = URM, modern food_proc = RC, etc.) > 'unknown'."],
        ["4. TIV precedence", "Building + Contents supplied → use as-is (SUPPLIED). Partial supply → fill missing components by class split ratio (PARTIAL). Nothing supplied → class-based notional × split ratio (ESTIMATED)."],
        ["5. Split ratios", "Office 60/25/15; Warehouse 60/30/10; Light Mfg 45/30/25; Heavy Mfg 40/30/30; Food Proc 40/30/30; Utility 40/30/30; Civic 70/20/10; Vacant 60/30/10 (Building / Contents / BI / Other)."],
        ["6. Peril coverage by state", "Geographic heuristic until policy wording supplies it. NY downstate: HU+ST+FL+WS+FR; LA/FL: HU+ST+FL+WF+FR; CA: EQ+WF+FR; IL: EQ+ST+WS+FL+FR (NMSZ); default ST+FR."],
        ["7. Secondary modifiers", "Class-based defaults for sprinkler / roof / soft-storey / basement / ext_wall when broker did not supply. Sprinkler % >= 50 → 'Y'."],
        ["8. Geocode level", "Decimal-precision heuristic: ≥4 dp → rooftop (L6); ≥3 dp → postcode (L4); ≥2 dp → city (L2); else admin (L1) / country (L0)."],
        ["9. Policy structure", "One notional blanket policy per legal entity: $500M blanket limit, $1M deductible, HU 2% / EQ 5% per-loc, 18-month BI indemnity period. Replace with deal-record terms in production."],
      ]);

    const buffer = await wb.xlsx.writeBuffer();
    return {
      statusCode: 200,
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "Content-Disposition": 'attachment; filename="CERA-RMS-EDM-Export.xlsx"',
      },
      body: Buffer.from(buffer).toString("base64"),
      isBase64Encoded: true,
    };
  } catch (err) {
    return { statusCode: 500, body: `export-edm error: ${err.message}` };
  }
};
